export EQUINNX_DIR=/home/allouche/Works/EquiNNx_22Aout
export EQUINNX_SRC=$EQUINNX_DIR/src
export EQUINNX_TOOLS=$EQUINNX_DIR/tools
export EQUINNX_SCRIPTS=$EQUINNX_DIR/scripts/Local
export PYTHONPATH=$PYTHONPATH:$EQUINNX_SRC
export PATH=$PATH:$EQUINNX_SRC
export PATH=$PATH:$EQUINNX_SCRIPTS
source ./env.sh
