#!/bin/bash

source config.sh

export CUDA_VISIBLE_DEVICES=""
fh5='evaluation.h5'
prefix='water'
python $EQUINNX_SRC/buildDataBatching.py --dataset=$fh5 --seed=10 --num_train=200 --num_valid=0 --batch_size=10 --num_workers=8 --save_data=1

