#!/bin/bash
source ./config.sh

DIRECTORIES=$(ls -d tmp/ |  tr '\n' ',')
export PREFIX=omat24
echo $DIRECTORIES
echo "=== Computing global E0s ===" 
time python compute_e0s.py --directories=$DIRECTORIES --output e0s.csv
    

