export EQUINNX_DIR=/home/allouche/MySoftwares/EquiNNx/EquiNNx-Polar-v2
export EQUINNX_SRC=$EQUINNX_DIR/src
export EQUINNX_TOOLS=$EQUINNX_DIR/tools
export EQUINNX_SCRIPTS=$EQUINNX_DIR/scripts/Local
export PYTHONPATH=$PYTHONPATH:$EQUINNX_SRC
export PATH=$PATH:$EQUINNX_SRC
export PATH=$PATH:$EQUINNX_SCRIPTS
source $EQUINNX_SCRIPTS/env.sh
