#!/bin/bash 

source config.sh
#export CUDA_VISIBLE_DEVICES='' # to force CPU use

export DISPLAY='' # to avoid display figures. Figures saved in .pdf

fnpz="evaluation.npz"
#fnpz="train_chk/metrics/best_valid_valid_set.npz"
prog=$EQUINNX_TOOLS/'analyze.py'
#prog='analyze.py'
fout='water'
buildfigures=1
python $prog $fnpz $fout $buildfigures
