#!/bin/bash

source config.sh
fnxyz='md17_ethanol.xyz'
prefix='md17_ethanol'
python buildData.py --build_index=1 --save_xyz_with_index=1 --save_xyz_without_index=0 --cutoff=-1 --input_file_name=$fnxyz --prefix=$prefix

