#!/bin/bash 

source config.sh
#export CUDA_VISIBLE_DEVICES='' # to force CPU use

export DISPLAY='' # to avoid display figures. Figures saved in .pdf

fnpz="evaluation.npz"
#fnpz="train_chk/metrics/best_valid_valid_set.npz"
prog=$EQUINNX_TOOLS/'rotateToPA.py'
fn=${fnpz%.npz}
python $prog --input_file_name=${fn}.npz --n_embeded_atoms=3 --output_file_name=${fn}_rotated.npz
#python $prog --input_file_name=${fn}.npz --n_embeded_atoms=-1 --output_file_name=rotated.npz
